model:
  name: "UNet_cGAN"
  in_channels: 6  # 3 RGB image + 3 (x, y, Î¸)
  out_channels: 3  # 3 RGB images
train:
  batch_size: 8
  epochs: 100
  learning_rate: 2e-4
  lambda_l1: 100
  lambda_coord: 10
paths:
  data_root: "./data"
  checkpoints: "./outputs/checkpoints"
  logs: "./outputs/logs"